# Generated by Django 5.2.4 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent_Product', '0004_remove_cliente_telefono_remove_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='producto',
            field=models.ManyToManyField(to='Invent_Product.producto'),
        ),
    ]
